# Generated by Django 5.2.8 on 2026-01-10 14:02

import django.core.validators
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        error_messages={
                            "min_length": "Nickname must be at least 2 chars long!"
                        },
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30, validators=[profiles.validators.name_validator]
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=30, validators=[profiles.validators.name_validator]
                    ),
                ),
                ("chef", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
