# Generated by Django 5.2.8 on 2026-01-09 07:35

import django.core.validators
import travelers.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="*Nicknames can contain only letters and digits.",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            travelers.validators.nickname_validator,
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=30, unique=True)),
                (
                    "country",
                    models.CharField(
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("about_me", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
