# Generated by Django 5.2.8 on 2025-12-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_and_time_of_publication",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
