# Generated by Django 5.2.8 on 2025-12-30 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_comment_date_and_time_of_publication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date_and_time_of_publication"]},
        ),
    ]
