# Generated by Django 5.2.8 on 2026-01-09 07:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("travelers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("summary", models.TextField()),
                ("start_date", models.DateField()),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="*Duration in days is expected."
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                (
                    "traveler",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="travelers.traveler",
                    ),
                ),
            ],
        ),
    ]
