# Generated by Django 5.2.8 on 2026-01-07 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "This fruit name is already in use! Try a new one."
                        },
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Fruit name should contain only letters!",
                                regex="^[a-zA-Z]+$",
                            ),
                        ],
                    ),
                ),
                ("image_url", models.URLField()),
                ("description", models.TextField()),
                ("nutrition", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fruits",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
