# Generated by Django 5.2.8 on 2026-01-08 07:30

import authors.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            authors.validators.name_validator,
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            authors.validators.name_validator,
                        ],
                    ),
                ),
                (
                    "passcode",
                    models.CharField(
                        help_text="Your passcode must be a combination of 6 digits",
                        validators=[authors.validators.password_validator],
                    ),
                ),
                ("info", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
