# Generated by Django 5.2.8 on 2026-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="pets_number",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
